package com.challenge.api.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.challenge.api.model.CreateEmployeeRequest;
import com.challenge.api.model.Employee;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.web.server.ResponseStatusException;

/**
 * Unit tests for employee creation, retrieval, deletion,
 * validation, and in-memory storage behavior.
 */
public class EmployeeServiceTest {

    @Test
    void getAllEmployeesShouldInitiallyBeEmpty() {
        EmployeeService employeeService = new EmployeeService();

        List<Employee> employees = employeeService.getAllEmployees();

        assertEquals(0, employees.size());
    }

    @Test
    void createEmployeeShouldCreateAndStoreEmployee() {
        EmployeeService employeeService = new EmployeeService();

        CreateEmployeeRequest request = new CreateEmployeeRequest();
        request.setFirstName("Sneha");
        request.setLastName("Patel");
        request.setSalary(85000);
        request.setAge(23);
        request.setJobTitle("Software Engineer");
        request.setEmail("sneha@example.com");

        Employee employee = employeeService.createEmployee(request);

        assertNotNull(
                employee.getUuid()); // UUID should be generated by the service rather than supplied by the request.
        assertEquals("Sneha", employee.getFirstName());
        assertEquals("Patel", employee.getLastName());
        assertEquals("Sneha Patel", employee.getFullName());
        assertEquals(85000, employee.getSalary());
        assertEquals(
                1,
                employeeService
                        .getAllEmployees()
                        .size()); // verify creation also persists the employee in the in-memory store.
    }

    @Test
    void getEmployeeByUuidShouldReturnEmployee() {
        EmployeeService employeeService = new EmployeeService();

        CreateEmployeeRequest request = new CreateEmployeeRequest();
        request.setFirstName("Sneha");
        request.setLastName("Patel");
        request.setSalary(85000);
        request.setAge(23);

        Employee createdEmployee = employeeService.createEmployee(request);

        Employee foundEmployee = employeeService.getEmployeeByUuid(createdEmployee.getUuid());

        assertEquals(createdEmployee.getUuid(), foundEmployee.getUuid());
        assertEquals("Sneha", foundEmployee.getFirstName());
        assertEquals("Patel", foundEmployee.getLastName());
    }

    @Test
    void getEmployeeByUuidShouldThrowWhenEmployeeDoesNotExist() {
        EmployeeService employeeService = new EmployeeService();

        UUID nonexistentUuid = UUID.randomUUID();

        assertThrows(ResponseStatusException.class, () -> employeeService.getEmployeeByUuid(nonexistentUuid));
    }

    @Test
    void deleteEmployeeShouldRemoveEmployee() {
        EmployeeService employeeService = new EmployeeService();

        CreateEmployeeRequest request = new CreateEmployeeRequest();
        request.setFirstName("Sneha");
        request.setLastName("Patel");
        request.setSalary(85000);
        request.setAge(23);

        Employee createdEmployee = employeeService.createEmployee(request);

        employeeService.deleteEmployee(createdEmployee.getUuid());

        assertEquals(
                0,
                employeeService.getAllEmployees().size()); // confirm the employee is no longer present after deletion.
    }
}
//./gradlew :api:spotlessApply
//./gradlew :api:test
